###

GET http://localhost:80/api/item?id=99
Accept: application/json

###
###
GET http://localhost:3000/user/all
Content-Type: application/json


### 注册
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "userName": "Yao123",
  "password": "123456",
  "realName": "YaoBing"
}

### 登录
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "userName": "Yao123",
  "password": "123456"
}

### 登录2
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "userName": "Yao123",
  "password": "123456"
}


### Authorization by token, part 1. Retrieve and save token.
GET http://localhost:3000/user/current
Content-Type: application/json
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IllhbzEyMyIsImlhdCI6MTU4OTE3ODgxNywiZXhwIjoxNTk0MzYyODE3fQ.BdX5Xc-2LfsmsC_XUrToCXlpLMPN8aP9PPXCZx6Iw6I
